const ROOT = 'customer'

export const ADD_CUSTOMERS_REQUEST = `${ROOT}/ADD_CUSTOMERS_REQUEST`;
export const ADD_CUSTOMERS_SUCCESS = `${ROOT}/ADD_CUSTOMERS_SUCCESS`;
export const ADD_CUSTOMERS_ERROR = `${ROOT}/ADD_CUSTOMERS_ERROR`;