const ROOT = 'customer'

export const GET_CUSTOMERS_REQUEST = `${ROOT}/GET_CUSTOMERS_REQUEST`;
export const GET_CUSTOMERS_SUCCESS = `${ROOT}/GET_CUSTOMERS_SUCCESS`;
export const GET_CUSTOMERS_ERROR = `${ROOT}/GET_CUSTOMERS_ERROR`;