const ROOT = 'customer'

export const UPDATE_CUSTOMERS_REQUEST = `${ROOT}/UPDATE_CUSTOMERS_REQUEST`;
export const UPDATE_CUSTOMERS_SUCCESS = `${ROOT}/UPDATE_CUSTOMERS_SUCCESS`;
export const UPDATE_CUSTOMERS_ERROR = `${ROOT}/UPDATE_CUSTOMERS_ERROR`;