const ROOT = 'customer'

export const DELETE_CUSTOMERS_REQUEST = `${ROOT}/DELETE_CUSTOMERS_REQUEST`;
export const DELETE_CUSTOMERS_SUCCESS = `${ROOT}/DELETE_CUSTOMERS_SUCCESS`;
export const DELETE_CUSTOMERS_ERROR = `${ROOT}/DELETE_CUSTOMERS_ERROR`;