const ROOT = 'customer'

export const AVERAGE_CUSTOMERS_REQUEST = `${ROOT}/AVERAGE_CUSTOMERS_REQUEST`;
export const AVERAGE_CUSTOMERS_SUCCESS = `${ROOT}/AVERAGE_CUSTOMERS_SUCCESS`;
export const AVERAGE_CUSTOMERS_ERROR = `${ROOT}/AVERAGE_CUSTOMERS_ERROR`;