const ROOT = 'customer'

export const AVERAGE_GENDER_REQUEST = `${ROOT}/AVERAGE_GENDER_REQUEST`;
export const AVERAGE_GENDER_SUCCESS = `${ROOT}/AVERAGE_GENDER_SUCCESS`;
export const AVERAGE_GENDER_ERROR = `${ROOT}/AVERAGE_GENDER_ERROR`;